version: 2.1

orbs:
  dwave: dwave/orb-examples@dev:dev

workflows:
  version: 2.1
  tests:
    jobs:
      - dwave/test-linux
      - dwave/test-osx
      - dwave/test-win

  # daily:
  #   triggers:
  #     - schedule:
  #         cron: "0 11 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #               - main
  #   jobs:
  #     - dwave/test-linux
  #     - dwave/test-osx
  #     - dwave/test-win
